#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateNeuseInventory
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nssnc")]
	public partial class ProductsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertproduct(product instance);
    partial void Updateproduct(product instance);
    partial void Deleteproduct(product instance);
    #endregion
		
		public ProductsDataContext() : 
				base(global::UpdateNeuseInventory.Properties.Settings.Default.nssncConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProductsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.products")]
	public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pID;
		
		private string _pName;
		
		private string _pName2;
		
		private string _pName3;
		
		private System.Nullable<int> _pSection;
		
		private System.Nullable<int> _pDropship;
		
		private string _pDescription;
		
		private string _pDescription2;
		
		private string _pDescription3;
		
		private string _pLongdescription;
		
		private string _pLongdescription2;
		
		private string _pLongdescription3;
		
		private string _pDownload;
		
		private System.Nullable<double> _pPrice;
		
		private System.Nullable<double> _pListPrice;
		
		private System.Nullable<double> _pWholesalePrice;
		
		private System.Nullable<double> _pShipping;
		
		private System.Nullable<double> _pShipping2;
		
		private System.Nullable<double> _pWeight;
		
		private System.Nullable<double> _pTax;
		
		private System.Nullable<byte> _pDisplay;
		
		private System.Nullable<byte> _pSell;
		
		private System.Nullable<bool> _pStaticPage;
		
		private System.Nullable<bool> _pStockByOpts;
		
		private System.Nullable<bool> _pRecommend;
		
		private System.Nullable<bool> _pGiftWrap;
		
		private System.Nullable<bool> _pBackOrder;
		
		private System.Nullable<int> _pOrder;
		
		private System.Nullable<int> _pManufacturer;
		
		private System.Nullable<byte> _pExemptions;
		
		private string _pDims;
		
		private string _pSKU;
		
		private string _pTitle;
		
		private string _pMetaDesc;
		
		private System.Nullable<System.DateTime> _pDateAdded;
		
		private System.Nullable<int> _pTotRating;
		
		private System.Nullable<int> _pNumRatings;
		
		private string _pSearchParams;
		
		private string _pCustom1;
		
		private string _pCustom2;
		
		private string _pCustom3;
		
		private string _pStaticURL;
		
		private System.Nullable<int> _pInStock;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpIDChanging(string value);
    partial void OnpIDChanged();
    partial void OnpNameChanging(string value);
    partial void OnpNameChanged();
    partial void OnpName2Changing(string value);
    partial void OnpName2Changed();
    partial void OnpName3Changing(string value);
    partial void OnpName3Changed();
    partial void OnpSectionChanging(System.Nullable<int> value);
    partial void OnpSectionChanged();
    partial void OnpDropshipChanging(System.Nullable<int> value);
    partial void OnpDropshipChanged();
    partial void OnpDescriptionChanging(string value);
    partial void OnpDescriptionChanged();
    partial void OnpDescription2Changing(string value);
    partial void OnpDescription2Changed();
    partial void OnpDescription3Changing(string value);
    partial void OnpDescription3Changed();
    partial void OnpLongdescriptionChanging(string value);
    partial void OnpLongdescriptionChanged();
    partial void OnpLongdescription2Changing(string value);
    partial void OnpLongdescription2Changed();
    partial void OnpLongdescription3Changing(string value);
    partial void OnpLongdescription3Changed();
    partial void OnpDownloadChanging(string value);
    partial void OnpDownloadChanged();
    partial void OnpPriceChanging(System.Nullable<double> value);
    partial void OnpPriceChanged();
    partial void OnpListPriceChanging(System.Nullable<double> value);
    partial void OnpListPriceChanged();
    partial void OnpWholesalePriceChanging(System.Nullable<double> value);
    partial void OnpWholesalePriceChanged();
    partial void OnpShippingChanging(System.Nullable<double> value);
    partial void OnpShippingChanged();
    partial void OnpShipping2Changing(System.Nullable<double> value);
    partial void OnpShipping2Changed();
    partial void OnpWeightChanging(System.Nullable<double> value);
    partial void OnpWeightChanged();
    partial void OnpTaxChanging(System.Nullable<double> value);
    partial void OnpTaxChanged();
    partial void OnpDisplayChanging(System.Nullable<byte> value);
    partial void OnpDisplayChanged();
    partial void OnpSellChanging(System.Nullable<byte> value);
    partial void OnpSellChanged();
    partial void OnpStaticPageChanging(System.Nullable<bool> value);
    partial void OnpStaticPageChanged();
    partial void OnpStockByOptsChanging(System.Nullable<bool> value);
    partial void OnpStockByOptsChanged();
    partial void OnpRecommendChanging(System.Nullable<bool> value);
    partial void OnpRecommendChanged();
    partial void OnpGiftWrapChanging(System.Nullable<bool> value);
    partial void OnpGiftWrapChanged();
    partial void OnpBackOrderChanging(System.Nullable<bool> value);
    partial void OnpBackOrderChanged();
    partial void OnpOrderChanging(System.Nullable<int> value);
    partial void OnpOrderChanged();
    partial void OnpManufacturerChanging(System.Nullable<int> value);
    partial void OnpManufacturerChanged();
    partial void OnpExemptionsChanging(System.Nullable<byte> value);
    partial void OnpExemptionsChanged();
    partial void OnpDimsChanging(string value);
    partial void OnpDimsChanged();
    partial void OnpSKUChanging(string value);
    partial void OnpSKUChanged();
    partial void OnpTitleChanging(string value);
    partial void OnpTitleChanged();
    partial void OnpMetaDescChanging(string value);
    partial void OnpMetaDescChanged();
    partial void OnpDateAddedChanging(System.Nullable<System.DateTime> value);
    partial void OnpDateAddedChanged();
    partial void OnpTotRatingChanging(System.Nullable<int> value);
    partial void OnpTotRatingChanged();
    partial void OnpNumRatingsChanging(System.Nullable<int> value);
    partial void OnpNumRatingsChanged();
    partial void OnpSearchParamsChanging(string value);
    partial void OnpSearchParamsChanged();
    partial void OnpCustom1Changing(string value);
    partial void OnpCustom1Changed();
    partial void OnpCustom2Changing(string value);
    partial void OnpCustom2Changed();
    partial void OnpCustom3Changing(string value);
    partial void OnpCustom3Changed();
    partial void OnpStaticURLChanging(string value);
    partial void OnpStaticURLChanged();
    partial void OnpInStockChanging(System.Nullable<int> value);
    partial void OnpInStockChanged();
    #endregion
		
		public product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pID", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pID
		{
			get
			{
				return this._pID;
			}
			set
			{
				if ((this._pID != value))
				{
					this.OnpIDChanging(value);
					this.SendPropertyChanging();
					this._pID = value;
					this.SendPropertyChanged("pID");
					this.OnpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pName", DbType="NVarChar(255)")]
		public string pName
		{
			get
			{
				return this._pName;
			}
			set
			{
				if ((this._pName != value))
				{
					this.OnpNameChanging(value);
					this.SendPropertyChanging();
					this._pName = value;
					this.SendPropertyChanged("pName");
					this.OnpNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pName2", DbType="NVarChar(255)")]
		public string pName2
		{
			get
			{
				return this._pName2;
			}
			set
			{
				if ((this._pName2 != value))
				{
					this.OnpName2Changing(value);
					this.SendPropertyChanging();
					this._pName2 = value;
					this.SendPropertyChanged("pName2");
					this.OnpName2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pName3", DbType="NVarChar(255)")]
		public string pName3
		{
			get
			{
				return this._pName3;
			}
			set
			{
				if ((this._pName3 != value))
				{
					this.OnpName3Changing(value);
					this.SendPropertyChanging();
					this._pName3 = value;
					this.SendPropertyChanged("pName3");
					this.OnpName3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pSection", DbType="Int")]
		public System.Nullable<int> pSection
		{
			get
			{
				return this._pSection;
			}
			set
			{
				if ((this._pSection != value))
				{
					this.OnpSectionChanging(value);
					this.SendPropertyChanging();
					this._pSection = value;
					this.SendPropertyChanged("pSection");
					this.OnpSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDropship", DbType="Int")]
		public System.Nullable<int> pDropship
		{
			get
			{
				return this._pDropship;
			}
			set
			{
				if ((this._pDropship != value))
				{
					this.OnpDropshipChanging(value);
					this.SendPropertyChanging();
					this._pDropship = value;
					this.SendPropertyChanged("pDropship");
					this.OnpDropshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDescription", DbType="NVarChar(MAX)")]
		public string pDescription
		{
			get
			{
				return this._pDescription;
			}
			set
			{
				if ((this._pDescription != value))
				{
					this.OnpDescriptionChanging(value);
					this.SendPropertyChanging();
					this._pDescription = value;
					this.SendPropertyChanged("pDescription");
					this.OnpDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDescription2", DbType="NVarChar(MAX)")]
		public string pDescription2
		{
			get
			{
				return this._pDescription2;
			}
			set
			{
				if ((this._pDescription2 != value))
				{
					this.OnpDescription2Changing(value);
					this.SendPropertyChanging();
					this._pDescription2 = value;
					this.SendPropertyChanged("pDescription2");
					this.OnpDescription2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDescription3", DbType="NVarChar(MAX)")]
		public string pDescription3
		{
			get
			{
				return this._pDescription3;
			}
			set
			{
				if ((this._pDescription3 != value))
				{
					this.OnpDescription3Changing(value);
					this.SendPropertyChanging();
					this._pDescription3 = value;
					this.SendPropertyChanged("pDescription3");
					this.OnpDescription3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pLongdescription", DbType="NVarChar(MAX)")]
		public string pLongdescription
		{
			get
			{
				return this._pLongdescription;
			}
			set
			{
				if ((this._pLongdescription != value))
				{
					this.OnpLongdescriptionChanging(value);
					this.SendPropertyChanging();
					this._pLongdescription = value;
					this.SendPropertyChanged("pLongdescription");
					this.OnpLongdescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pLongdescription2", DbType="NVarChar(MAX)")]
		public string pLongdescription2
		{
			get
			{
				return this._pLongdescription2;
			}
			set
			{
				if ((this._pLongdescription2 != value))
				{
					this.OnpLongdescription2Changing(value);
					this.SendPropertyChanging();
					this._pLongdescription2 = value;
					this.SendPropertyChanged("pLongdescription2");
					this.OnpLongdescription2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pLongdescription3", DbType="NVarChar(MAX)")]
		public string pLongdescription3
		{
			get
			{
				return this._pLongdescription3;
			}
			set
			{
				if ((this._pLongdescription3 != value))
				{
					this.OnpLongdescription3Changing(value);
					this.SendPropertyChanging();
					this._pLongdescription3 = value;
					this.SendPropertyChanged("pLongdescription3");
					this.OnpLongdescription3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDownload", DbType="NVarChar(255)")]
		public string pDownload
		{
			get
			{
				return this._pDownload;
			}
			set
			{
				if ((this._pDownload != value))
				{
					this.OnpDownloadChanging(value);
					this.SendPropertyChanging();
					this._pDownload = value;
					this.SendPropertyChanged("pDownload");
					this.OnpDownloadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pPrice", DbType="Float")]
		public System.Nullable<double> pPrice
		{
			get
			{
				return this._pPrice;
			}
			set
			{
				if ((this._pPrice != value))
				{
					this.OnpPriceChanging(value);
					this.SendPropertyChanging();
					this._pPrice = value;
					this.SendPropertyChanged("pPrice");
					this.OnpPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pListPrice", DbType="Float")]
		public System.Nullable<double> pListPrice
		{
			get
			{
				return this._pListPrice;
			}
			set
			{
				if ((this._pListPrice != value))
				{
					this.OnpListPriceChanging(value);
					this.SendPropertyChanging();
					this._pListPrice = value;
					this.SendPropertyChanged("pListPrice");
					this.OnpListPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pWholesalePrice", DbType="Float")]
		public System.Nullable<double> pWholesalePrice
		{
			get
			{
				return this._pWholesalePrice;
			}
			set
			{
				if ((this._pWholesalePrice != value))
				{
					this.OnpWholesalePriceChanging(value);
					this.SendPropertyChanging();
					this._pWholesalePrice = value;
					this.SendPropertyChanged("pWholesalePrice");
					this.OnpWholesalePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pShipping", DbType="Float")]
		public System.Nullable<double> pShipping
		{
			get
			{
				return this._pShipping;
			}
			set
			{
				if ((this._pShipping != value))
				{
					this.OnpShippingChanging(value);
					this.SendPropertyChanging();
					this._pShipping = value;
					this.SendPropertyChanged("pShipping");
					this.OnpShippingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pShipping2", DbType="Float")]
		public System.Nullable<double> pShipping2
		{
			get
			{
				return this._pShipping2;
			}
			set
			{
				if ((this._pShipping2 != value))
				{
					this.OnpShipping2Changing(value);
					this.SendPropertyChanging();
					this._pShipping2 = value;
					this.SendPropertyChanged("pShipping2");
					this.OnpShipping2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pWeight", DbType="Float")]
		public System.Nullable<double> pWeight
		{
			get
			{
				return this._pWeight;
			}
			set
			{
				if ((this._pWeight != value))
				{
					this.OnpWeightChanging(value);
					this.SendPropertyChanging();
					this._pWeight = value;
					this.SendPropertyChanged("pWeight");
					this.OnpWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pTax", DbType="Float")]
		public System.Nullable<double> pTax
		{
			get
			{
				return this._pTax;
			}
			set
			{
				if ((this._pTax != value))
				{
					this.OnpTaxChanging(value);
					this.SendPropertyChanging();
					this._pTax = value;
					this.SendPropertyChanged("pTax");
					this.OnpTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDisplay", DbType="TinyInt")]
		public System.Nullable<byte> pDisplay
		{
			get
			{
				return this._pDisplay;
			}
			set
			{
				if ((this._pDisplay != value))
				{
					this.OnpDisplayChanging(value);
					this.SendPropertyChanging();
					this._pDisplay = value;
					this.SendPropertyChanged("pDisplay");
					this.OnpDisplayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pSell", DbType="TinyInt")]
		public System.Nullable<byte> pSell
		{
			get
			{
				return this._pSell;
			}
			set
			{
				if ((this._pSell != value))
				{
					this.OnpSellChanging(value);
					this.SendPropertyChanging();
					this._pSell = value;
					this.SendPropertyChanged("pSell");
					this.OnpSellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pStaticPage", DbType="Bit")]
		public System.Nullable<bool> pStaticPage
		{
			get
			{
				return this._pStaticPage;
			}
			set
			{
				if ((this._pStaticPage != value))
				{
					this.OnpStaticPageChanging(value);
					this.SendPropertyChanging();
					this._pStaticPage = value;
					this.SendPropertyChanged("pStaticPage");
					this.OnpStaticPageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pStockByOpts", DbType="Bit")]
		public System.Nullable<bool> pStockByOpts
		{
			get
			{
				return this._pStockByOpts;
			}
			set
			{
				if ((this._pStockByOpts != value))
				{
					this.OnpStockByOptsChanging(value);
					this.SendPropertyChanging();
					this._pStockByOpts = value;
					this.SendPropertyChanged("pStockByOpts");
					this.OnpStockByOptsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pRecommend", DbType="Bit")]
		public System.Nullable<bool> pRecommend
		{
			get
			{
				return this._pRecommend;
			}
			set
			{
				if ((this._pRecommend != value))
				{
					this.OnpRecommendChanging(value);
					this.SendPropertyChanging();
					this._pRecommend = value;
					this.SendPropertyChanged("pRecommend");
					this.OnpRecommendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pGiftWrap", DbType="Bit")]
		public System.Nullable<bool> pGiftWrap
		{
			get
			{
				return this._pGiftWrap;
			}
			set
			{
				if ((this._pGiftWrap != value))
				{
					this.OnpGiftWrapChanging(value);
					this.SendPropertyChanging();
					this._pGiftWrap = value;
					this.SendPropertyChanged("pGiftWrap");
					this.OnpGiftWrapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pBackOrder", DbType="Bit")]
		public System.Nullable<bool> pBackOrder
		{
			get
			{
				return this._pBackOrder;
			}
			set
			{
				if ((this._pBackOrder != value))
				{
					this.OnpBackOrderChanging(value);
					this.SendPropertyChanging();
					this._pBackOrder = value;
					this.SendPropertyChanged("pBackOrder");
					this.OnpBackOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pOrder", DbType="Int")]
		public System.Nullable<int> pOrder
		{
			get
			{
				return this._pOrder;
			}
			set
			{
				if ((this._pOrder != value))
				{
					this.OnpOrderChanging(value);
					this.SendPropertyChanging();
					this._pOrder = value;
					this.SendPropertyChanged("pOrder");
					this.OnpOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pManufacturer", DbType="Int")]
		public System.Nullable<int> pManufacturer
		{
			get
			{
				return this._pManufacturer;
			}
			set
			{
				if ((this._pManufacturer != value))
				{
					this.OnpManufacturerChanging(value);
					this.SendPropertyChanging();
					this._pManufacturer = value;
					this.SendPropertyChanged("pManufacturer");
					this.OnpManufacturerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pExemptions", DbType="TinyInt")]
		public System.Nullable<byte> pExemptions
		{
			get
			{
				return this._pExemptions;
			}
			set
			{
				if ((this._pExemptions != value))
				{
					this.OnpExemptionsChanging(value);
					this.SendPropertyChanging();
					this._pExemptions = value;
					this.SendPropertyChanged("pExemptions");
					this.OnpExemptionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDims", DbType="NVarChar(255)")]
		public string pDims
		{
			get
			{
				return this._pDims;
			}
			set
			{
				if ((this._pDims != value))
				{
					this.OnpDimsChanging(value);
					this.SendPropertyChanging();
					this._pDims = value;
					this.SendPropertyChanged("pDims");
					this.OnpDimsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pSKU", DbType="NVarChar(255)")]
		public string pSKU
		{
			get
			{
				return this._pSKU;
			}
			set
			{
				if ((this._pSKU != value))
				{
					this.OnpSKUChanging(value);
					this.SendPropertyChanging();
					this._pSKU = value;
					this.SendPropertyChanged("pSKU");
					this.OnpSKUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pTitle", DbType="NVarChar(255)")]
		public string pTitle
		{
			get
			{
				return this._pTitle;
			}
			set
			{
				if ((this._pTitle != value))
				{
					this.OnpTitleChanging(value);
					this.SendPropertyChanging();
					this._pTitle = value;
					this.SendPropertyChanged("pTitle");
					this.OnpTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pMetaDesc", DbType="NVarChar(255)")]
		public string pMetaDesc
		{
			get
			{
				return this._pMetaDesc;
			}
			set
			{
				if ((this._pMetaDesc != value))
				{
					this.OnpMetaDescChanging(value);
					this.SendPropertyChanging();
					this._pMetaDesc = value;
					this.SendPropertyChanged("pMetaDesc");
					this.OnpMetaDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pDateAdded", DbType="DateTime")]
		public System.Nullable<System.DateTime> pDateAdded
		{
			get
			{
				return this._pDateAdded;
			}
			set
			{
				if ((this._pDateAdded != value))
				{
					this.OnpDateAddedChanging(value);
					this.SendPropertyChanging();
					this._pDateAdded = value;
					this.SendPropertyChanged("pDateAdded");
					this.OnpDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pTotRating", DbType="Int")]
		public System.Nullable<int> pTotRating
		{
			get
			{
				return this._pTotRating;
			}
			set
			{
				if ((this._pTotRating != value))
				{
					this.OnpTotRatingChanging(value);
					this.SendPropertyChanging();
					this._pTotRating = value;
					this.SendPropertyChanged("pTotRating");
					this.OnpTotRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pNumRatings", DbType="Int")]
		public System.Nullable<int> pNumRatings
		{
			get
			{
				return this._pNumRatings;
			}
			set
			{
				if ((this._pNumRatings != value))
				{
					this.OnpNumRatingsChanging(value);
					this.SendPropertyChanging();
					this._pNumRatings = value;
					this.SendPropertyChanged("pNumRatings");
					this.OnpNumRatingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pSearchParams", DbType="NVarChar(255)")]
		public string pSearchParams
		{
			get
			{
				return this._pSearchParams;
			}
			set
			{
				if ((this._pSearchParams != value))
				{
					this.OnpSearchParamsChanging(value);
					this.SendPropertyChanging();
					this._pSearchParams = value;
					this.SendPropertyChanged("pSearchParams");
					this.OnpSearchParamsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pCustom1", DbType="NVarChar(255)")]
		public string pCustom1
		{
			get
			{
				return this._pCustom1;
			}
			set
			{
				if ((this._pCustom1 != value))
				{
					this.OnpCustom1Changing(value);
					this.SendPropertyChanging();
					this._pCustom1 = value;
					this.SendPropertyChanged("pCustom1");
					this.OnpCustom1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pCustom2", DbType="NVarChar(255)")]
		public string pCustom2
		{
			get
			{
				return this._pCustom2;
			}
			set
			{
				if ((this._pCustom2 != value))
				{
					this.OnpCustom2Changing(value);
					this.SendPropertyChanging();
					this._pCustom2 = value;
					this.SendPropertyChanged("pCustom2");
					this.OnpCustom2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pCustom3", DbType="NVarChar(255)")]
		public string pCustom3
		{
			get
			{
				return this._pCustom3;
			}
			set
			{
				if ((this._pCustom3 != value))
				{
					this.OnpCustom3Changing(value);
					this.SendPropertyChanging();
					this._pCustom3 = value;
					this.SendPropertyChanged("pCustom3");
					this.OnpCustom3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pStaticURL", DbType="NVarChar(255)")]
		public string pStaticURL
		{
			get
			{
				return this._pStaticURL;
			}
			set
			{
				if ((this._pStaticURL != value))
				{
					this.OnpStaticURLChanging(value);
					this.SendPropertyChanging();
					this._pStaticURL = value;
					this.SendPropertyChanged("pStaticURL");
					this.OnpStaticURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pInStock", DbType="Int")]
		public System.Nullable<int> pInStock
		{
			get
			{
				return this._pInStock;
			}
			set
			{
				if ((this._pInStock != value))
				{
					this.OnpInStockChanging(value);
					this.SendPropertyChanging();
					this._pInStock = value;
					this.SendPropertyChanged("pInStock");
					this.OnpInStockChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
